INSERT INTO drzave (naziv)
VALUES
        ('Afganistan'),
        ('Albanija'),
        ('Alžir'),
        ('Andora'),
        ('Angola'),
        ('Antigva i Barbuda'),
        ('Argentina'),
        ('Armenija'),
        ('Australija'),
        ('Austrija'),
        ('Azerbajdžan'),
        ('Bahami'),
        ('Bahrein'),
        ('Bangladeš'),
        ('Belarus'),
        ('Belgija'),
        ('Belize'),
        ('Benin'),
        ('Bjelarus'),
        ('Bjelokosna Obala'),
        ('Bjelorusija'),
        ('Bocvana'),
        ('Bolivija'),
        ('Bosna i Hercegovina'),
        ('Brazil'),
        ('Brunej'),
        ('Brunej Darussalam'),
        ('Bugarska'),
        ('Burkina Faso'),
        ('Burma'),
        ('Burundi'),
        ('Butan'),
        ('Cipar'),
        ('Crna Gora'),
        ('Čad'),
        ('Češka'),
        ('Čile'),
        ('Danska'),
        ('Koreja'),
        ('DR Kongo'),
        ('Dominika'),
        ('Dominikana'),
        ('Dominikanska Republika'),
        ('Đibuti'),
        ('Dž'),
        ('Džibuti'),
        ('Egipat'),
        ('El Salvador'),
        ('Ekvador'),
        ('Ekvatorska Gvineja'),
        ('Eritreja'),
        ('Estonija'),
        ('Etiopija'),
        ('Fidži'),
        ('Filipini'),
        ('Finska'),
        ('Francuska'),
        ('Gabon'),
        ('Gambija'),
        ('Gana'),
        ('Grčka'),
        ('Grenada'),
        ('Gruzija'),
        ('Gvajana'),
        ('Gvatemala'),
        ('Gvineja'),
        ('Gvineja Bisau'),
        ('Haiti'),
        ('Honduras'),
        ('Hrvatska'),
        ('Indija'),
        ('Indonezija'),
        ('Irak'),
        ('Iran'),
        ('Irska'),
        ('Island'),
        ('Istočni Timor'),
        ('Italija'),
        ('Izrael'),
        ('Jamajka'),
        ('Japan'),
        ('Jemen'),
        ('Jordan'),
        ('Južna Afrika'),
        ('Južna Koreja'),
        ('Južni Sudan'),
        ('Južnoafrička Republika'),
        ('Kabo Verde'),
        ('Kambodža'),
        ('Kamerun'),
        ('Kanada'),
        ('Katar'),
        ('Kazahstan'),
        ('Kazakstan'),
        ('Kenija'),
        ('NR Kina'),
        ('Kirgistan'),
        ('Kiribati'),
        ('Kolumbija'),
        ('Kongo'),
        ('Demokratska Republika Kongo'),
        ('Republika Kongo'),
        ('Koreja'),
        ('Demokratska Narodna Republika Koreja (Sjeverna Koreja)'),
        ('Republika Koreja (Južna Koreja)'),
        ('Kosovo'),
        ('Kostarika'),
        ('Kuba'),
        ('Kuvajt'),
        ('Laos'),
        ('Latvija'),
        ('Lesoto'),
        ('Letonija'),
        ('Libanon'),
        ('Liberija'),
        ('Libija'),
        ('Lihtenštajn'),
        ('Litva'),
        ('Luksemburg'),
        ('Madagaskar'),
        ('Madžarska'),
        ('Mađarska'),
        ('Makedonija'),
        ('Malavi'),
        ('Maldivi'),
        ('Malezija'),
        ('Mali'),
        ('Malta'),
        ('Maroko'),
        ('Maršalovi Otoci'),
        ('Mauricijus'),
        ('Mauretanija'),
        ('Mauritanija'),
        ('Meksiko'),
        ('Mianma'),
        ('Mianmar'),
        ('Mijanmar'),
        ('Mikronezija'),
        ('Mjanma'),
        ('Mjanmar'),
        ('Moldavija'),
        ('Moldova'),
        ('Monako'),
        ('Mongolija'),
        ('Mozambik'),
        ('Namibija'),
        ('Nauru'),
        ('Nepal'),
        ('Niger'),
        ('Nigerija'),
        ('Nikaragva'),
        ('Nizozemska'),
        ('Norveška'),
        ('Novi Zeland'),
        ('Njemačka'),
        ('Oman'),
        ('Obala Bjelokosti'),
        ('Pakistan'),
        ('Palau'),
        ('Panama'),
        ('Papua Nova Gvineja'),
        ('Paragvaj'),
        ('Peru'),
        ('Poljska'),
        ('Portugal'),
        ('Republika Kongo'),
        ('Republika Koreja'),
        ('Ruanda'),
        ('Rumunjska'),
        ('Rusija'),
        ('Federacija'),
        ('Salomonski Otoci'),
        ('Salvador'),
        ('Samoa'),
        ('San Marino'),
        ('Saudijska Arabija'),
        ('Sejšeli'),
        ('Senegal'),
        ('Sijera Leone'),
        ('Singapur'),
        ('Sirija'),
        ('Sjedinjene Američke Države'),
        ('Sjeverna Koreja'),
        ('Sjeverna Makedonija'),
        ('Slovačka'),
        ('Slovenija'),
        ('Solomonovo Otočje'),
        ('Solomonski Otoci'),
        ('Somalija'),
        ('Srbija'),
        ('Srednjoafrička Republika'),
        ('Sudan'),
        ('Surinam'),
        ('Svazi'),
        ('Sveta Lucija'),
        ('Sveti Kristofor i Nevis'),
        ('Sveti Toma i Princip'),
        ('Sveti Vincent i Grenadini'),
        ('Španjolska'),
        ('Šri Lanka'),
        ('Švedska'),
        ('Švicarska'),
        ('Tadžikistan'),
        ('Tajland'),
        ('Tanzanija'),
        ('Timor-Leste'),
        ('Togo'),
        ('Tonga'),
        ('Trinidad i Tobago'),
        ('Tunis'),
        ('Turkmenistan'),
        ('Turska'),
        ('Tuvalu'),
        ('Uganda'),
        ('Ujedinjeni Arapski Emirati'),
        ('Ujedinjeno Kraljevstvo'),
        ('Ukrajina'),
        ('Urugvaj'),
        ('Uzbekistan'),
        ('Vanuatu'),
        ('Vatikan'),
        ('Velika Britanija'),
        ('Venezuela'),
        ('Vijetnam'),
        ('Zair'),
        ('Zambija'),
        ('Zapadna Samoa'),
        ('Zelenortska Republika'),
        ('Zimbabve');
