INSERT INTO jezici (ime)
VALUES
    ('Abhaski jezik'),
    ('Afarski jezik'),
    ('Afrikaans'),
    ('Ajmarski jezik'),
    ('Albanski jezik'),
    ('Akanski jezik'),
    ('Amharski jezik'),
    ('Aragonski jezik'),
    ('Aramejski jezik'),
    ('Arapski jezik'),
    ('Asamski jezik'),
    ('Asturleonski jezik'),
    ('Avarski jezik'),
    ('Avestički jezik'),
    ('Azerski jezik'),
    ('Bambarski jezik'),
    ('Baskijski jezik'),
    ('Baškirski jezik'),
    ('Bengalski jezik'),
    ('Biharski jezik'),
    ('Bislama jezik'),
    ('Bjeloruski jezik'),
    ('Bošnjački jezik'),
    ('Bretonski jezik'),
    ('Bugarski jezik'),
    ('Bura'),
    ('Chamorro jezik'),
    ('Crkvenoslavenski jezik'),
    ('Crnogorski jezik'),
    ('Čečenski jezik'),
    ('Češki jezik'),
    ('Čulimski jezik'),
    ('Čuvaški jezik'),
    ('Dalmatski jezik'),
    ('Danski jezik'),
    ('Dhivehi jezik'),
    ('Donjolužičkosrpski jezik'),
    ('Donjonjemački jezici'),
    ('Donjosaski jezik'),
    ('Dzongkha jezik'),
    ('Engleski jezik'),
    ('Esperanto'),
    ('Estonski jezik'),
    ('Etruščanski jezik'),
    ('Eve jezik'),
    ('Flamanski jezik'),
    ('Fenički jezik'),
    ('Finski jezik'),
    ('Francuski jezik'),
    ('Frizijski jezici'),
    ('Galicijski jezik'),
    ('Gornjolužičkosrpski jezik'),
    ('Gornjenjemački jezik'),
    ('Grčki jezik'),
    ('Gruzijski jezik'),
    ('Hatski jezik'),
    ('Hebrejski jezik'),
    ('Hetitski jezik'),
    ('Hindski jezik'),
    ('Hrvatski jezik'),
    ('Hurijski jezik'),
    ('Ido'),
    ('Interlingua'),
    ('Irski jezik'),
    ('Islandski jezik'),
    ('Japanski jezik'),
    ('Kašubski jezik'),
    ('Katalanski jezik'),
    ('Kazaški jezik'),
    ('Kineski jezik'),
    ('Kirgiški jezik'),
    ('Koptski jezik'),
    ('Kornski jezik'),
    ('Korzički jezik'),
    ('Laponski jezik'),
    ('Latinski jezik'),
    ('Latvijski jezik'),
    ('Litavski jezik'),
    ('Luksemburški jezik'),
    ('Lužičkosrpski jezici'),
    ('Mađarski jezik'),
    ('Makedonski jezik'),
    ('Malteški jezik'),
    ('Moldavski jezik'),
    ('Mandarinski jezik'),
    ('Nizozemski jezik'),
    ('Norveški jezik'),
    ('Novogrčki jezik'),
    ('Njemački jezik'),
    ('Okcitanski jezik'),
    ('Perzijski jezik'),
    ('Polabski jezik'),
    ('Poljski jezik'),
    ('Portugalski jezik'),
    ('Retoromanski jezik'),
    ('Romski jezik'),
    ('Rumunjski jezik'),
    ('Rusinski jezik'),
    ('Ruski jezik'),
    ('Sanskrt'),
    ('Slavenosrpski jezik'),
    ('Slovački jezik'),
    ('Slovenski jezik'),
    ('Slovio'),
    ('Spelin'),
    ('Srpski jezik'),
    ('Starocrkvenoslavenski jezik'),
    ('Starogrčki jezik'),
    ('Sumerski jezik'),
    ('Suržik'),
    ('Škotski galski jezik'),
    ('Škotski jezik'),
    ('Španjolski jezik'),
    ('Švedski jezik'),
    ('Talijanski jezik'),
    ('Trasjanka'),
    ('Turski jezik'),
    ('Tuvanski jezik'),
    ('Ukrajinski jezik'),
    ('Urdu jezik'),
    ('Uzbečki jezik'),
    ('Velški jezik'),
    ('Volapük'),
    ('Zulu');